ci: add verify workflow

diff --git a/.github/workflows/macos_ci.yml b/.github/workflows/macos_ci.yml
--- a/.github/workflows/macos_ci.yml
+++ b/.github/workflows/macos_ci.yml
@@ -1,30 +1,46 @@
 name: CI macOS
+run-name: ${{ github.event.workflow_run.head_commit.message }}
 
 on:
-  push:
-    paths-ignore:
-      - '**.md'
-      - '**.yml'
-      - '!**/macos_ci.yml'
-  pull_request:
-    paths-ignore:
-      - '**.md'
-      - '**.yml'
-      - '!**/macos_ci.yml'
+  workflow_run:
+    workflows: ['Verify']
+    types: [completed]
 
 concurrency:
   group: macos-ci-${{ github.event.pull_request.number || github.sha }}
   cancel-in-progress: true
 
 jobs:
+  check-relevance:
+    runs-on: ubuntu-20.04
+    if: github.event_name != 'push' || github.event.ref == 'refs/heads/master' || github.event.repository.full_name != 'vlang/v'
+    outputs:
+      any_changed: ${{ steps.changed-files.outputs.any_changed }}
+    steps:
+      - name: Exit on verification failure
+        if: ${{ github.event.workflow_run.conclusion == 'failure' }}
+        run: echo 'Code verification failed' && exit 1
+      - uses: actions/checkout@v4
+      - name: Check changed files
+        id: changed-files
+        uses: tj-actions/changed-files@v44
+        with:
+          files: |
+            !**.md
+            !**.yml
+            **/macos_ci.yml
+
   clang:
     runs-on: macOS-12
-    if: github.event_name != 'push' || github.event.ref == 'refs/heads/master' || github.event.repository.full_name != 'vlang/v'
+    needs: check-relevance
+    if: needs.check-relevance.outputs.any_changed == 'true' && (github.event_name != 'push' || github.event.ref == 'refs/heads/master' || github.event.repository.full_name != 'vlang/v')
     timeout-minutes: 121
     env:
       VFLAGS: -cc clang
       PKG_CONFIG_PATH: /usr/local/opt/pkgconfig:/usr/local/opt/libpq/lib/pkgconfig:/usr/local/opt/openssl@3/lib/pkgconfig:/opt/homebrew/lib/pkgconfig:/opt/homebrew/opt/libpq/lib/pkgconfig:/opt/homebrew/opt/openssl@3/lib/pkgconfig
     steps:
+      - if: ${{ github.event.workflow_run.conclusion == 'failure' }}
+        run: echo 'Code verification failed' && exit 1
       - uses: actions/checkout@v4
       - name: Install dependencies
         run: |
